# Generated by Django 5.1.6 on 2025-03-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
    ]
